pipeline:

  test-dbg-gcc-8-sund-4.1.0:
    image: bjodah/bjodahimg18:v2.1
    group: testing
    environment:
      - CPATH=/usr/include/suitesparse
      - CC=gcc-8
      - CXX=g++-8
      - SUNDBASE=/opt/sundials-4.1.0-klu-lapack
      - CHEMREAC_INTEGRATION_KWARGS="dict(integrator='cvode')" 
    commands:
      - bash -c "source .ci/copy_tree.sh /tmp/ci $SUNDBASE; pwd; .ci/run_tests.sh chemreac --cov chemreac --cov-report html"

  test-rel-gcc-7-sund-3.2.1:
    image: bjodah/bjodahimg18:v2.1
    group: testing
    environment:
      - CPATH=/usr/include/suitesparse
      - CC=gcc-7
      - CXX=g++-7
      - SUNDBASE=/opt/sundials-3.2.1-klu-lapack
    commands:
      - bash -c "source .ci/copy_tree.sh /tmp/ci $SUNDBASE; pwd; .ci/run_tests.sh"

  test-conda-pkgs:
    image: bjodah/bjodahimg18dev:v2.1
    commands:
      - ./scripts/coverage_badge.py htmlcov/ htmlcov/coverage.svg
      - ./scripts/generate_docs.sh
      - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
      - ./scripts/prepare_deploy.sh
      - PATH=/opt/miniconda3/bin:$PATH conda config --add channels bjodah  # sym, pyodesys, pyneqsys
      - PATH=/opt/miniconda3/bin:$PATH conda build --output-folder "deploy/public_html/branches/${CI_BRANCH}" conda-recipe
      - if grep --exclude ".drone.yml" "DO-NOT-MERGE!" -R .; then exit 1; fi

  deploy:
    image: drillster/drone-rsync
    when:
      event: [push]
    hosts: [ "hera.physchem.kth.se" ]  # 127.0.0.1  192.168.1.99 davycrockett.mooo.com
    port: 22
    user: chemreac
    secrets: [ rsync_key ]  # secret only set fro event "push" not "pull_request"
    source: ./deploy/public_html
    target: ~/
