image: bjodah/dockerfile-bjodah-scicomp
git:
    path: github.com/chemreac/chemreac
env:
  - WITH_OPENMP=1
  - CHEMREAC_SOLVER=sundials
  - CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH:/usr/include/python2.7"
script:
  - pip install pyodeint pygslodeiv2
  - ./scripts/run_tests.sh
