pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./ci_cache/pip_cache
      - ./ci_cache/pyusrb
    volumes:
      - /tmp/cache:/cache
    ttl: 90  # liftetime in days

  install-reqs:
    image: bjodah/bjodahimg18:v2.2
    environment:
      - PYCVODES_LAPACK=lapack,blas
      - PYCVODES_SUNDIALS_LIBS=sundials_cvodes,sundials_nvecserial,sundials_sunlinsollapackdense,sundials_sunlinsollapackband,sundials_sunlinsolklu
      - PYCVODES_NO_KLU=0
      - CPATH=/usr/include/suitesparse
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu
    commands:
      - export CPATH=$SUNDBASE/include:$CPATH
      - export LIBRARY_PATH=$SUNDBASE/lib:$LIBRARY_PATH
      - export LD_LIBRARY_PATH=$SUNDBASE/lib:$LD_LIBRARY_PATH
      - export PYTHONUSERBASE=$(pwd)/ci_cache/pyusrb
      - mkdir -p $PYTHONUSERBASE
      - python3 -m pip install --user --cache-dir ./ci_cache/pip_cache --upgrade finitediff "block_diag_ilu>=0.3.10,<0.4.0"

  test-dbg-gcc-8-sund-3.2.1:
    image: bjodah/bjodahimg18:v2.2
    group: testing
    environment:
      - CPATH=/usr/include/suitesparse
      - CC=gcc-8
      - CXX=g++-8
      - SUNDBASE=/opt/sundials-3.2.1-klu-lapack
      - CHEMREAC_INTEGRATION_KWARGS="dict(integrator='cvode')" 
    commands:
      - bash -c "source .ci/copy_tree.sh /tmp/ci $SUNDBASE; pwd; .ci/run_tests.sh chemreac --cov chemreac --cov-report html"

  test-rel-gcc-7-sund-2.7.0:
    image: bjodah/bjodahimg18:v2.2
    group: testing
    environment:
      - CPATH=/usr/include/suitesparse
      - CC=gcc-7
      - CXX=g++-7
      - SUNDBASE=/opt/sundials-2.7.0-klu-lapack
    commands:
      - bash -c "source .ci/copy_tree.sh /tmp/ci $SUNDBASE; pwd; .ci/run_tests.sh"

  test-conda-pkgs:
    image: bjodah/bjodahimg18dev:v2.1
    commands:
      - ./scripts/coverage_badge.py htmlcov/ htmlcov/coverage.svg
      - ./scripts/generate_docs.sh
      - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
      - ./scripts/prepare_deploy.sh
      - PATH=/opt/miniconda3/bin:$PATH conda config --add channels bjodah  # sym, pyodesys, pyneqsys
      - PATH=/opt/miniconda3/bin:$PATH conda build --output-folder "deploy/public_html/branches/${CI_BRANCH}" conda-recipe
      - if grep --exclude ".drone.yml" "DO-NOT-MERGE!" -R .; then exit 1; fi

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./ci_cache/pip_cache
      - ./ci_cache/pyusrb
    volumes:
      - /tmp/cache:/cache

  deploy:
    image: drillster/drone-rsync
    when:
      event: [push]
    hosts: [ "hera.physchem.kth.se" ]  # 127.0.0.1  192.168.1.99 davycrockett.mooo.com
    port: 22
    user: chemreac
    secrets: [ rsync_key ]  # secret only set fro event "push" not "pull_request"
    source: ./deploy/public_html
    target: ~/
