clone:
  depth: 2
  recursive: true
  submodule_override:
    external/anyode: git://github.com/bjodah/anyode.git

cache:
  mount:
    - /drone/sundials-3.2.0

build:
  image: bjodah/bjodahimg18dev:v1.3
  environment:
    - ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-6.0/bin/llvm-symbolizer
    - ASAN_OPTIONS=symbolize=1
    - WITH_OPENMP=1
    - CPATH=/drone/sundials-3.2.0/include
    - LIBRARY_PATH=/drone/sundials-3.2.0/lib
    - LD_LIBRARY_PATH=/drone/sundials-3.2.0/lib
    - PYCVODES_LAPACK=lapack,blas
    - PYCVODES_SUNDIALS_LIBS=sundials_cvodes,sundials_nvecserial,sundials_sunlinsollapackdense,sundials_sunlinsollapackband
    - PYCVODES_NO_KLU=1
  commands:
    - python3 -m pip install --upgrade "matplotlib>=2.2.3,<3.0.0"
    - git fetch -tq  # used by ``git describe``
    - if [ ! -d /drone/sundials-3.2.0 ]; then .ci/get_sundials.sh 3.2.0 /drone/sundials-3.2.0 -DLAPACK_ENABLE:BOOL=ON -DSUNDIALS_INDEX_TYPE:STRING="int32_t"; fi
    - CHEMREAC_INTEGRATION_KWARGS="dict(integrator='cvode')" ./scripts/ci.sh chemreac
    - python3 setup.py build_ext -i
    - ./scripts/run_tests.sh chemreac --cov chemreac --cov-report html
    - ./scripts/coverage_badge.py htmlcov/ htmlcov/coverage.svg
    - ./scripts/generate_docs.sh
    - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/prepare_deploy.sh
    - PATH=/opt/miniconda3/bin:$PATH conda config --add channels bjodah  # sym, pyodesys, pyneqsys
    - PATH=/opt/miniconda3/bin:$PATH conda build --output-folder "deploy/public_html/branches/${CI_BRANCH}" conda-recipe
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: chemreac
    source: deploy/
    target: ~
    recursive: true
    delete: false
