cache:
  mount:
    - /drone/sundials-3.1

build:
  image: bjodah/bjodahimg18dev:v1.0
  environment:
    - WITH_OPENMP=1
    - CPATH=/drone/sundials-3.1/include
    - LIBRARY_PATH=/drone/sundials-3.1/lib
    - LD_LIBRARY_PATH=/drone/sundials-3.1/lib
  commands:
    - if [ ! -d /drone/sundials-3.1 ]; then .ci/download_and_install_sundials-3.1.sh /drone/sundials-3.1; fi
    - python3 -m pip install --ignore-installed --no-deps quantities==0.12.1
    - PYCVODES_LAPACK=lapack,blas ./scripts/ci.sh chemreac
    - CHEMREAC_INTEGRATION_KWARGS="dict(integrator='cvode')" ./scripts/run_tests.sh chemreac --cov chemreac --cov-report html
    - ./scripts/coverage_badge.py htmlcov/ htmlcov/coverage.svg
    - ./scripts/generate_docs.sh
    - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/prepare_deploy.sh
    - PATH=/opt/miniconda3/bin:$PATH conda config --add channels bjodah  # sym, pyodesys, pyneqsys
    - PATH=/opt/miniconda3/bin:$PATH conda build conda-recipe
    - if grep "DO-NOT-MERGE!" -R . --exclude ".drone.yml"; then exit 1; fi

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: chemreac
    source: deploy/
    target: ~
    recursive: true
    delete: false
