export LIBRARY_PATH="$PREFIX/lib:$LIBRARY_PATH"
export CPLUS_INCLUDE_PATH="$PREFIX/include:$INCLUDE_PATH"

export WITH_OPENMP=1
export WITH_BLOCK_DIAG_ILU_DGETRF=1
export WITH_BLOCK_DIAG_ILU_OPENMP=1
$PYTHON setup.py build

$PYTHON setup.py install
