package:
  name: chemreac
  version: "0.2.1"
  # the version is actually being set by the __conda_version__.txt file
  # http://conda.pydata.org/docs/build.html#post-build-version

source:
  url: https://github.com/bjodah/chemreac/archive/master.zip

requirements:
  build:
    - python
    - cython
    - numpy
    - patchelf
    - pycompilation
    - pycodeexport
    - mako
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - future
    - sympy

test:
  requires:
    - pytest
    - sympy
  commands:
    - py.test

about:
  home: https://github.com/bjodah/chemreac
  license: BSD License
