package:
  name: chemreac
  version: 0.6.0.git
  # the version being overridden by the __conda_version__.txt file
  # http://conda.pydata.org/docs/build.html#post-build-version

source:
  path: ../

requirements:
  build:
    - python
    - sundials
    - cython
    - numpy
    - pycompilation
    - pycodeexport
    - mako
    - block_diag_ilu
    - quantities
    - chempy
    - lapack
  run:
    - python
    - numpy
    - scipy
    - sundials
    - matplotlib
    - sympy
    - quantities
    - chempy
    - block_diag_ilu
    - lapack

build:
  number: 0

test:
  requires:
    - pytest
    - periodictable
    - argh
  imports:
    - chemreac
  commands:
    - MPLBACKEND=Agg py.test --pyargs chemreac

about:
  home: https://github.com/chemreac/chemreac
  license: BSD License
  summary: Python package for modelling chemical kinetics with diffusion and drift
