{% set name = "chemreac" %}
{% set version = "0.7.12dev0+git" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 200
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - toolchain
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20*  # [not win]
    - python
    - setuptools
    - pip
    - cython
    - sundials
    - mako
    - quantities >=0.12.1
    - pycompilation
    - pycodeexport >=0.1.2
    - block_diag_ilu >=0.3.9,<0.4.0
    - finitediff >=0.6.2
    - pycvodes >=0.10.11,<0.11.0
    - numpy 1.11.*
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas 0.2.20*  # [not win]
    - python
    - cython
    - numpy >=1.11
    - scipy
    - sundials
    - mako
    - quantities >=0.12.1
    - pycompilation
    - pycodeexport >=0.1.2
    - block_diag_ilu >=0.3.9,<0.4.0
    - finitediff >=0.6.2
    - pycvodes >=0.10.11,<0.11.0
    - pyodesys >=0.11.16,<0.12.0
    - chempy >=0.6.8,<0.7.0

test:
  requires:
    - periodictable
    - argh
    - pytest
  imports:
    - chemreac
    - chemreac.util
  commands:
    - MPLBACKEND=Agg python -m pytest --pyargs chemreac

about:
  home: https://chemreac.github.io/
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python package for modelling chemical kinetics with diffusion and drift'
  doc_url: https://chemreac.github.io/docs/master/
  dev_url: https://github.com/chemreac/chemreac

extra:
  recipe-maintainers:
    - bjodah
